<div class="search-box white grey-border-left grey-top-bottom-border">
  <input class="validate left" id="LocationText" name="LocationText" placeholder="Plaats of postcode" type="text" value="" />
   <div id="AutocompleteWrapper"></div>
   <div class="select-wrapper other-option radio hide-me-im-fake">
     <span class="caret">▼</span>
     <input type="text" class="select-dropdown truncate check valid grey-border-left" readonly="true" data-activates="select-options-e5e0c705-fa31-8ff3-84ae-45a5c79f7921" value="+ 0 km" aria-invalid="false">
     <ul id="select-options-e5e0c705-fa31-8ff3-84ae-45a5c79f7921" class="dropdown-content select-dropdown" style="width: 89px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;"><li class=""><span>+ 0 km</span></li><li class=""><span>+ 1 km</span></li><li class=""><span>+ 2 km</span></li><li class=""><span>+ 5 km</span></li><li class=""><span>+ 10 km</span></li><li class=""><span>+ 20 km</span></li></ul><select class="other-option radio inbox-radius hide-on-med-and-down initialized" data-for="RadiusId" data-val="true" data-val-number="The field RadiusId must be a number." id="RadiusId" name="RadiusId"><option selected="selected" value="1">+ 0 km</option></select></div> <select class="search-filter-data other-option radio inbox-radius hide-on-med-and-down grey-border-right" data-for="RadiusId" data-val="true" data-val-number="The field RadiusId must be a number." id="RadiusId" name="RadiusId"><option selected="selected" value="1">+ 0 km</option>
<option value="2">+ 1 km</option>
<option value="3">+ 2 km</option>
<option value="4">+ 5 km</option>
<option value="5">+ 10 km</option>
<option value="7">+ 20 km</option>
</select> <div class="right btn kamernet-bluegreen white-text z-depth-0" onclick="performSearch();"><i class="fa fa-search" aria-hidden="true"></i></div><div class="error-message hiddendiv" id="PostalCodeCityErrorMessage" hidden="hidden">ERR_POSTALCODE_OR_CITY_NOT_FOUND</div></div></div><div class="col s5 hide-on-med-and-down"><div class="top-search-filters z-depth-0"><div class="col s12 no-padding center"><div class="col s4 no-padding-left grey-border"><div class="top-filter-rent"><div class="select-wrapper other-option radio price-other hide-me-im-fake"><span class="caret">▼</span><input type="text" class="select-dropdown truncate check valid" readonly="true" data-activates="select-options-c4e766e1-9880-a2d7-f056-b0ea715dcbf0" value="€ 6.000" aria-invalid="false"><ul id="select-options-c4e766e1-9880-a2d7-f056-b0ea715dcbf0" class="dropdown-content select-dropdown" style="width: 139px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;"><li class=""><span>Anders</span></li><li class=""><span>€ 100</span></li><li class=""><span>€ 200</span></li><li class=""><span>€ 300</span></li><li class=""><span>€ 400</span></li><li class=""><span>€ 500</span></li><li class=""><span>€ 600</span></li><li class=""><span>€ 700</span></li><li class=""><span>€ 800</span></li><li class=""><span>€ 900</span></li><li class=""><span>€ 1.000</span></li><li class=""><span>€ 1.100</span></li><li class=""><span>€ 1.200</span></li><li class=""><span>€ 1.300</span></li><li class=""><span>€ 1.400</span></li><li class=""><span>€ 1.500</span></li><li class=""><span>€ 1.750</span></li><li class=""><span>€ 2.000</span></li><li class=""><span>€ 2.250</span></li><li class=""><span>€ 2.500</span></li><li class=""><span>€ 2.750</span></li><li class=""><span>€ 3.000</span></li><li class=""><span>€ 3.250</span></li><li class=""><span>€ 3.500</span></li><li class=""><span>€ 3.750</span></li><li class=""><span>€ 4.000</span></li><li class=""><span>€ 4.250</span></li><li class=""><span>€ 4.500</span></li><li class=""><span>€ 4.750</span></li><li class=""><span>€ 5.000</span></li><li class=""><span>€ 5.250</span></li><li class=""><span>€ 5.500</span></li><li class=""><span>€ 5.750</span></li><li class=""><span>€ 6.000</span></li><li class=""><span>Geen</span></li></ul><select class="other-option radio price-other initialized " data-val="true" data-val-number="The field RentalPriceId must be a number." data-val-required="The RentalPriceId field is required." id="RentalPriceId" name="RentalPriceId"><option value="">Anders</option><option selected="selected" value="33">€ -</option></select></div> <select class="search-filter-data other-option radio price-other" data-val="true" data-val-number="The field RentalPriceId must be a number." data-val-required="The RentalPriceId field is required." id="RentalPriceId" name="RentalPriceId"><option value="">€ -</option>
<option value="1">€ 100</option>
<option value="2">€ 200</option>
<option value="3">€ 300</option>
<option value="4">€ 400</option>
<option value="5">€ 500</option>
<option value="6">€ 600</option>
<option value="7">€ 700</option>
<option value="8">€ 800</option>
<option value="9">€ 900</option>
<option value="10">€ 1.000</option>
<option value="11">€ 1.100</option>
<option value="12">€ 1.200</option>
<option value="13">€ 1.300</option>
<option value="14">€ 1.400</option>
<option value="15">€ 1.500</option>
<option value="16">€ 1.750</option>
<option value="17">€ 2.000</option>
<option value="18">€ 2.250</option>
<option value="19">€ 2.500</option>
<option value="20">€ 2.750</option>
<option value="21">€ 3.000</option>
<option value="22">€ 3.250</option>
<option value="23">€ 3.500</option>
<option value="24">€ 3.750</option>
<option value="25">€ 4.000</option>
<option value="26">€ 4.250</option>
<option value="27">€ 4.500</option>
<option value="28">€ 4.750</option>
<option value="29">€ 5.000</option>
<option value="30">€ 5.250</option>
<option value="31">€ 5.500</option>
<option value="32">€ 5.750</option>
<option value="33">€ 6.000</option>
<option value="34">Geen</option>
</select> </div></div><div class="col s4 no-padding-left grey-top-bottom-border"><div class="top-filter-surface"><div class="select-wrapper other-option radio hide-me-im-fake"><span class="caret">▼</span><input type="text" class="select-dropdown truncate check valid" readonly="true" data-activates="select-options-7db4fcf1-1d92-f5d7-4702-8bc6396f4809" value="32 m2" aria-invalid="false"><ul id="select-options-7db4fcf1-1d92-f5d7-4702-8bc6396f4809" class="dropdown-content select-dropdown" style="width: 139px; position: absolute; top: 0px; left: 0px; opacity: 1; display: none;"><li class=""><span>Anders</span></li><li class=""><span>6 m2</span></li><li class=""><span>8 m2</span></li><li class=""><span>10 m2</span></li><li class=""><span>12 m2</span></li><li class=""><span>14 m2</span></li><li class=""><span>16 m2</span></li><li class=""><span>18 m2</span></li><li class=""><span>20 m2</span></li><li class=""><span>22 m2</span></li><li class=""><span>24 m2</span></li><li class=""><span>26 m2</span></li><li class=""><span>28 m2</span></li><li class=""><span>30 m2</span></li><li class=""><span>32 m2</span></li><li class=""><span>34 m2</span></li><li class=""><span>36 m2</span></li><li class=""><span>38 m2</span></li><li class=""><span>40 m2</span></li><li class=""><span>45 m2</span></li><li class=""><span>50 m2</span></li><li class=""><span>60 m2</span></li><li class=""><span>70 m2</span></li><li class=""><span>80 m2</span></li><li class=""><span>90 m2</span></li><li class=""><span>100 m2</span></li></ul><select class="other-option radio initialized" data-for="SurfaceId" data-val="true" data-val-number="The field SurfaceId must be a number." data-val-required="The SurfaceId field is required." id="SurfaceId" name="SurfaceId"><option value="">Anders</option><option selected="selected" value="15">6 m2</option></select></div> <select class="search-filter-data other-option radio" data-for="SurfaceId" data-val="true" data-val-number="The field SurfaceId must be a number." data-val-required="The SurfaceId field is required." id="SurfaceId" name="SurfaceId"><option value="">- m2</option>
<option selected="selected" value="2">6 m2</option>
<option value="3">8 m2</option>
<option value="4">10 m2</option>
<option value="5">12 m2</option>
<option value="6">14 m2</option>
<option value="7">16 m2</option>
<option value="8">18 m2</option>
<option value="9">20 m2</option>
<option value="10">22 m2</option>
<option value="11">24 m2</option>
<option value="12">26 m2</option>
<option value="13">28 m2</option>
<option value="14">30 m2</option>
<option value="15">32 m2</option>
<option value="16">34 m2</option>
<option value="17">36 m2</option>
<option value="18">38 m2</option>
<option value="19">40 m2</option>
<option value="20">45 m2</option>
<option value="21">50 m2</option>
<option value="22">60 m2</option>
<option value="23">70 m2</option>
<option value="24">80 m2</option>
<option value="25">90 m2</option>
<option value="26">100 m2</option>
</select> </div></div><div class="col s4 no-padding js-toggle-right-slidebar grey-border"><div class="top-filters-number"><div id="filters-selected-total" class="kamernet-orange white-text top-filters-number-circle">0</div><span>filters</span></div></div></div></div></div></div></div><div class="row top-search-row-switch"><div class="col s12 m12 l8 offset-l2 no-padding-right-mobile"><div class="col s4 no-padding-left"><div class="switch-view"><div class="col s12 no-padding center"><div class="col s6 l4 no-padding hide-on-med-and-down white grey-border"><div id="tile-filter" class="list-switch waves-effect waves-block kamernet-blue-text strong current-item" onclick="switchView('Tile');"><i class="fa fa-th" aria-hidden="true"></i><span> Tegel</span></div></div><div class="col s6 l4 no-padding hide-on-med-and-down white grey-top-bottom-border"><div id="list-filter" class="list-switch waves-effect waves-block middle-item " onclick="switchView('List');"><i class="fa fa-list" aria-hidden="true"></i><span> Lijst</span></div></div>  <div class="col s12 l4 no-padding map-switch-col white grey-border" onclick="switchView('Map');"><div id="map-filter" class="map-switch waves-effect waves-block"><i class="fa fa-map-o" aria-hidden="true"></i><span> Kaart</span></div></div>  </div></div></div><div class="col s4 create-alert-wrapper no-padding-left"><div id="createAlertContainer" class="center"><a href="#" onclick="createAlert()" class="create-alert-btn white grey-border"><i class="fa fa-bell-o" aria-hidden="true"></i><span class="hide-on-med-and-down"> Bewaar je zoekopdracht</span><span class="hide-on-large-only"> Bewaar</span></a></div></div><div class="col s4 no-padding-left hide-on-large-only js-toggle-right-slidebar"><div class="top-filters-number center grey-border"><span id="filters-selected-total-mobile"></span> filter(s) </div></div></div></div>  <div off-canvas="slidebar-2 right overlay" id="sidebar-search-filters" class="white kamernet-grey-text"><div class="position-relative" style="height:100%;"><div id="sidebar-header-container"><div id="sidebar-header"><div class="row no-margin" style="cursor:pointer;"><div class="col s12 white center filters-mobile-actions no-padding"><div class="col s2 white-text kamernet-orange white-text" onclick="performSearch();"><i class="mdi-action-search big-text"></i><div class="filters-number kamernet-blue circle tiny-text" id="filters-selected">0</div></div><div class="col s8" onclick="performSearch();"><div class="uppercase" style="padding-top:15px">Zoekfilters</div></div><div class="col s2 js-close-right-slidebar"><div><i class="mdi-navigation-close big-text"></i></div></div></div></div></div></div><div id="sidebar-container"><div id="sidebar-content"><div class="row"><div class="col s12">  <style> #filters-advanced-panel-sidebar .submenu-basic .collapsible-body { padding: 10px 30px; } #filters-advanced-panel-sidebar .submenu-advanced .collapsible-body { padding: 10px; } #filters-advanced-panel-sidebar .submenu-basic .collapsible-header, #filters-advanced-panel-sidebar .submenu-advanced .collapsible-header { border-bottom: none; } #filters-advanced-panel-sidebar .submenu-basic .collapsible-header-title-span, #filters-advanced-panel-sidebar .submenu-advanced .collapsible-header-title-span { font-size: 16px; color: #656561; border-bottom: 1px dotted #6a6a64; } #filters-advanced-panel-sidebar .submenu-basic .collapsible-body-title, #filters-advanced-panel-sidebar .submenu-advanced .collapsible-body-title { color:#656561; font-size: 14px; font-weight:500; padding-bottom:5px !important; } #filters-advanced-panel-sidebar .submenu-advanced .km-checkbox [type="checkbox"]+label { min-width: 88px; padding: 6px 3%; } #filters-advanced-panel-sidebar .submenu-basic .select-wrapper input.select-dropdown { width:139px; } #filters-advanced-panel-sidebar .submenu-advanced .select-wrapper input.select-dropdown { height:17px; } .select-wrapper span.caret { pointer-events:none; } #filters-advanced-panel-sidebar .submenu-advanced .filters-availability-date { max-width: 76% !important; } </style><div id="filters-advanced-panel-sidebar">  <div class="col s12 sidebar-small-select hide-on-large-only"><div class="col s12 no-padding">Radius</div> <select class="other-option radio search-filter-data" data-for="RadiusId" id="RadiusId" name="RadiusId"><option selected="selected" value="1">+ 0 km</option>
<option value="2">+ 1 km</option>
<option value="3">+ 2 km</option>
<option value="4">+ 5 km</option>
<option value="5">+ 10 km</option>
<option value="7">+ 20 km</option>
</select> </div>  <div class="col s6 sidebar-small-select hide-on-large-only"><div class="col s12 no-padding truncate">Min. oppervlakte</div> <select class="other-option radio search-filter-data" data-for="SurfaceId" id="SurfaceId" name="SurfaceId"><option value="">- m2</option>
<option selected="selected" value="2">6 m2</option>
<option value="3">8 m2</option>
<option value="4">10 m2</option>
<option value="5">12 m2</option>
<option value="6">14 m2</option>
<option value="7">16 m2</option>
<option value="8">18 m2</option>
<option value="9">20 m2</option>
<option value="10">22 m2</option>
<option value="11">24 m2</option>
<option value="12">26 m2</option>
<option value="13">28 m2</option>
<option value="14">30 m2</option>
<option value="15">32 m2</option>
<option value="16">34 m2</option>
<option value="17">36 m2</option>
<option value="18">38 m2</option>
<option value="19">40 m2</option>
<option value="20">45 m2</option>
<option value="21">50 m2</option>
<option value="22">60 m2</option>
<option value="23">70 m2</option>
<option value="24">80 m2</option>
<option value="25">90 m2</option>
<option value="26">100 m2</option>
</select> </div><div class="col s6 sidebar-small-select hide-on-large-only"><div class="col s12 no-padding">Max. prijs</div> <select class="other-option radio price-other search-filter-data" id="RentalPriceId" name="RentalPriceId"><option value="">€ -</option>
<option value="1">€ 100</option>
<option value="2">€ 200</option>
<option value="3">€ 300</option>
<option value="4">€ 400</option>
<option value="5">€ 500</option>
<option value="6">€ 600</option>
<option value="7">€ 700</option>
<option value="8">€ 800</option>
<option value="9">€ 900</option>
<option value="10">€ 1.000</option>
<option value="11">€ 1.100</option>
<option value="12">€ 1.200</option>
<option value="13">€ 1.300</option>
<option value="14">€ 1.400</option>
<option value="15">€ 1.500</option>
<option value="16">€ 1.750</option>
<option value="17">€ 2.000</option>
<option value="18">€ 2.250</option>
<option value="19">€ 2.500</option>
<option value="20">€ 2.750</option>
<option value="21">€ 3.000</option>
<option value="22">€ 3.250</option>
<option value="23">€ 3.500</option>
<option value="24">€ 3.750</option>
<option value="25">€ 4.000</option>
<option value="26">€ 4.250</option>
<option value="27">€ 4.500</option>
<option value="28">€ 4.750</option>
<option value="29">€ 5.000</option>
<option value="30">€ 5.250</option>
<option value="31">€ 5.500</option>
<option value="32">€ 5.750</option>
<option value="33">€ 6.000</option>
<option value="34">Geen</option>
</select> </div><div class="col s12"><a class="right kamernet-bluegreen-text underline" id="resetAllFilters">Reset filters</a></div><div class="clearfix"><div class="divider"></div></div><ul class="collapsible z-depth-0 left-align no-border submenu-advanced" data-collapsible="expandable"><li><div id="roomDetails" class="collapsible-header transparent no-padding"><div class="led-green left"></div><strong class="collapsible-header-title-span">Woningdetails</strong></div><div class="collapsible-body"><div class="sub-section collapsible-body-title">Type woonruimte</div><div class="">  <div class="col s6 no-padding-left"> <input check="False" id="RoomTypeId_Kamer" name="RoomTypeId[]" type="checkbox" value="1" /> <label id="lbl_RoomTypeId_1" for="RoomTypeId_Kamer">Kamer</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="RoomTypeId_Appartement" name="RoomTypeId[]" type="checkbox" value="2" /> <label id="lbl_RoomTypeId_2" for="RoomTypeId_Appartement">Appartement</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="RoomTypeId_Studio" name="RoomTypeId[]" type="checkbox" value="4" /> <label id="lbl_RoomTypeId_4" for="RoomTypeId_Studio">Studio</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="RoomTypeId_Anti-kraak" name="RoomTypeId[]" type="checkbox" value="8" /> <label id="lbl_RoomTypeId_8" for="RoomTypeId_Anti-kraak">Anti-kraak</label></div>  </div><div class="clearfix sub-section collapsible-body-title">Oplevering</div><div class="furnishing">  <div class="col s12 no-padding-left"> <input check="False" id="FurnishingId_1" name="FurnishingId" type="checkbox" value="1" /> <label for="FurnishingId_1">Kaal</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="FurnishingId_2" name="FurnishingId" type="checkbox" value="2" /> <label for="FurnishingId_2">Gestoffeerd</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="FurnishingId_4" name="FurnishingId" type="checkbox" value="4" /> <label for="FurnishingId_4">Gemeubileerd</label></div>  </div><div class="clearfix sub-section collapsible-body-title">Faciliteiten</div><div class="facilities">  <div class="col s12 no-padding-left"> <input id="OwnShower" name="OwnShower" type="checkbox" value="True" /> <label for="OwnShower">Priv&#233;-badkamer</label></div>  <div class="col s12 no-padding-left"> <input id="OwnToilet" name="OwnToilet" type="checkbox" value="True" /> <label for="OwnToilet">Priv&#233;-toilet</label></div>  <div class="col s12 no-padding-left"> <input id="OwnKitchen" name="OwnKitchen" type="checkbox" value="True" /> <label for="OwnKitchen">Priv&#233;-keuken</label></div>  <div class="col s12 no-padding-left"> <input id="InternetAvailable" name="InternetAvailable" type="checkbox" value="True" /> <label for="InternetAvailable">Internet beschikbaar</label></div>  </div><div class="clearfix inner-filter-extra-margin"></div></div></li><li><div id="availabilityRoom" class="collapsible-header transparent no-padding"><div class="led-green left"></div><strong class="collapsible-header-title-span">Beschikbaarheid</strong></div><div class="collapsible-body"><div class="availability">  <div class="col s12 no-padding-left"> <input check="False" id="RentalPeriodId_1" name="RentalPeriodId" type="checkbox" value="1" /> <label for="RentalPeriodId_1">Onbepaalde tijd</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="RentalPeriodId_2" name="RentalPeriodId" type="checkbox" value="2" /> <label for="RentalPeriodId_2">Tijdelijk</label></div>  </div><div class="filters-availability-date no-padding clearfix"><div class="input-field"> <input class="datepicker" data-val="true" data-val-date="The field AvailableFromDate must be a date." id="AvailableFromDate" name="AvailableFromDate" type="text" value="" /> <span class="field-validation-valid" data-valmsg-for="AvailableFromDate" data-valmsg-replace="true"></span> <label for="AvailableFromDate" style="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36">Beschikbaar vanaf</label></div></div></div></li><li><div id="suitableRoom" class="collapsible-header transparent no-padding"><div class="led-green left"></div><strong class="collapsible-header-title-span">Geschikt voor</strong></div><div class="collapsible-body" style="overflow:hidden;"><div class="col s12 no-padding-left collapsible-body-title">Aantal zoekenden</div><div class="col s12 no-padding-left-mobile"><div class="suitable-for-number"> <select class="other-option radio price-other" id="SuitableForNumberOfPersonsId__" name="SuitableForNumberOfPersonsId[]"><option>-</option>
<option value="1">1 persoon</option>
<option value="2">2 personen</option>
<option value="4">3 personen</option>
<option value="8">4 personen</option>
<option value="16">5 personen</option>
<option value="17">&gt; 5 personen</option>
</select> </div></div><div class="col s12 no-padding-left collapsible-body-title">Geslacht</div><div class="col s12 no-padding-left-mobile">  <div class="col s6 no-padding-left"> <input check="False" id="SuitableForGendersId_1" name="SuitableForGendersId" type="checkbox" value="1" /> <label for="SuitableForGendersId_1">Man</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="SuitableForGendersId_2" name="SuitableForGendersId" type="checkbox" value="2" /> <label for="SuitableForGendersId_2">Vrouw</label></div>  </div><div class="inner-filter-extra-margin clearfix"></div><div class="col s12 no-padding-left collapsible-body-title">Leeftijd</div><div class="col s12 age-dropdown no-padding-left-mobile"> <select class="other-option radio" data-for="CandidateAge" id="CandidateAge__" name="CandidateAge[]"><option>-</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
<option value="39">39</option>
<option value="40">40</option>
<option value="41">41</option>
<option value="42">42</option>
<option value="43">43</option>
<option value="44">44</option>
<option value="45">45</option>
<option value="46">46</option>
<option value="47">47</option>
<option value="48">48</option>
<option value="49">49</option>
<option value="50">50</option>
<option value="51">51</option>
<option value="52">52</option>
<option value="53">53</option>
<option value="54">54</option>
<option value="55">55</option>
<option value="56">56</option>
<option value="57">57</option>
<option value="58">58</option>
<option value="59">59</option>
<option value="60">60</option>
<option value="61">61</option>
<option value="62">62</option>
<option value="63">63</option>
<option value="64">64</option>
<option value="65">65</option>
<option value="66">66</option>
<option value="67">67</option>
<option value="68">68</option>
<option value="69">69</option>
<option value="70">70</option>
<option value="71">71</option>
<option value="72">72</option>
<option value="73">73</option>
<option value="74">74</option>
<option value="75">75</option>
<option value="76">76</option>
<option value="77">77</option>
<option value="78">78</option>
<option value="79">79</option>
<option value="80">80</option>
<option value="81">81</option>
<option value="82">82</option>
<option value="83">83</option>
<option value="84">84</option>
<option value="85">85</option>
<option value="86">86</option>
<option value="87">87</option>
<option value="88">88</option>
<option value="89">89</option>
<option value="90">90</option>
<option value="91">91</option>
<option value="92">92</option>
<option value="93">93</option>
<option value="94">94</option>
<option value="95">95</option>
<option value="96">96</option>
<option value="97">97</option>
<option value="98">98</option>
<option value="99">99</option>
</select> </div><div class="inner-filter-extra-margin clearfix"></div><div class="col s12 no-padding-left collapsible-body-title">Status</div><div class="col s12 no-padding-left-mobile status">  <div class="col s12 no-padding-left"> <input check="False" id="SuitableForStatusesId_1" name="SuitableForStatusesId[]" type="checkbox" value="1" /> <label for="SuitableForStatusesId_1">Student</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="SuitableForStatusesId_2" name="SuitableForStatusesId[]" type="checkbox" value="2" /> <label for="SuitableForStatusesId_2">Werkende student</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="SuitableForStatusesId_4" name="SuitableForStatusesId[]" type="checkbox" value="4" /> <label for="SuitableForStatusesId_4">Werkend</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="SuitableForStatusesId_8" name="SuitableForStatusesId[]" type="checkbox" value="8" /> <label for="SuitableForStatusesId_8">Werkzoekend</label></div>  </div><div class="inner-filter-extra-margin"></div><div class="col s12 no-padding-left collapsible-body-title">Overig</div><div class="col s12 no-padding-left-mobile other">  <div class="col s12 no-padding-left"> <input id="SmokingInsideAllowed" name="SmokingInsideAllowed" type="checkbox" value="True" /> <label for="SmokingInsideAllowed">Roken toegestaan</label></div>  <div class="col s12 no-padding-left"> <input id="PetsInsideAllowed" name="PetsInsideAllowed" type="checkbox" value="True" /> <label for="PetsInsideAllowed">Huisdieren toegestaan</label></div>  </div></div></li>  <li><div id="generalRoom" class="collapsible-header transparent no-padding"><div class="led-green left"></div><strong class="collapsible-header-title-span">Overig</strong></div><div class="collapsible-body"><div class="col s12 no-padding-left collapsible-body-title"> Aantal huisgenoten </div><div class="col s12 no-padding-left-mobile status"> <select class="other-option radio" data-for="RoommateMaxNumberId" id="RoommateMaxNumberId__" name="RoommateMaxNumberId[]"><option>-</option>
<option value="1">Geen</option>
<option value="16">Max.4</option>
<option value="256">Max.8</option>
<option value="512">Meer dan 8</option>
</select> </div><div class="inner-filter-divider"></div><div class="col s12 no-padding-left collapsible-body-title"> Geslacht huisgenoten </div><div class="col s12 no-padding-left-mobile"><div class="room-type left">  <div class="col s6 no-padding-left"> <input check="False" id="RoommateGenderId_1" name="RoommateGenderId" type="checkbox" value="1" /> <label for="RoommateGenderId_1">Man</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="RoommateGenderId_2" name="RoommateGenderId" type="checkbox" value="2" /> <label for="RoommateGenderId_2">Vrouw</label></div>  <div class="col s6 no-padding-left"> <input check="False" id="RoommateGenderId_4" name="RoommateGenderId" type="checkbox" value="4" /> <label for="RoommateGenderId_4">Gemengd</label></div>  </div></div><div class="inner-filter-divider"></div><div class="inner-filter-divider"></div><div class="col s12 no-padding-left collapsible-body-title">Type aanbieder</div><div class="col s12 no-padding-left-mobile"><div class="owner-type">  <div class="col s12 no-padding-left"> <input check="False" id="OwnerTypeId_2" name="OwnerTypeId" type="checkbox" value="2" /> <label for="OwnerTypeId_2">Huisgenoot</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="OwnerTypeId_1" name="OwnerTypeId" type="checkbox" value="1" /> <label for="OwnerTypeId_1">Particuliere verhuurder</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="OwnerTypeId_4" name="OwnerTypeId" type="checkbox" value="4" /> <label for="OwnerTypeId_4">Makelaar</label></div>  <div class="col s12 no-padding-left"> <input check="False" id="OwnerTypeId_8" name="OwnerTypeId" type="checkbox" value="8" /> <label for="OwnerTypeId_8">Anders</label></div>  </div></div><div class="inner-filter-divider"></div><div class="col s12 no-padding-left collapsible-body-title">Inschrijfkosten</div><div class="col s12 no-padding-left-mobile">  <div class="col s6 no-padding-left"> <input id="NoRegistrationCosts" name="NoRegistrationCosts" type="checkbox" value="True" /> <label for="NoRegistrationCosts">Nee</label></div>  </div><div class="inner-filter-divider"></div><div class="clearfix"></div><div class="col s12 no-padding-left valign collapsible-body-title">Maximale extra kosten</div><div class="col s12 age-dropdown no-padding-left-mobile"> <select class="other-option radio" data-for="ExtraCostMax" id="ExtraCostMax__" name="ExtraCostMax[]"><option value="">-</option>
<option value="0">€ 0</option>
<option value="100">€ 100</option>
<option value="200">€ 200</option>
<option value="300">€ 300</option>
<option value="400">€ 400</option>
<option value="500">€ 500</option>
</select> </div><div class="clearfix"></div></div></li></ul></div> </div></div></div></div><div id="sidebar-footer-container" onclick="performSearch();" style="cursor:pointer;"><div id="sidebar-footer"><div class="row sidebar-bottom-bar kamernet-orange white-text"><div class="col s1"><i class="mdi-action-search"></i></div><div class="col s11" id="search-filter-total-results">Toon zoekresultaten: 4560</div></div></div></div></div></div> </form>   <div class="search-result-wrapper-row"><div class="container">  <div class="row sort-row"><div class="col s12 m12 l8 offset-l2 ">  <div class="sort-wrapper"><div class="col s4 l3 no-padding-left"><div class="select-wrapper search-filter-data other-option radio sort-dropdown hide-me-im-fake"><span class="caret">▼</span><input type="text" class="select-dropdown truncate check" readonly="true" data-activates="select-options-f439d9b3-d740-efcf-de70-94fc4fd2646f" value="Nieuwste eerst"><ul id="select-options-f439d9b3-d740-efcf-de70-94fc4fd2646f" class="dropdown-content select-dropdown "><li class=""><span>Nieuwste eerst</span></li><li class=""><span>Prijs oplopend</span></li><li class=""><span>Prijs aflopend</span></li><li class=""><span>Oppervlakte</span></li><li class=""><span>Beschikbaar per</span></li><li class=""><span>Facebook connecties</span></li></ul><select class="search-filter-data other-option radio sort-dropdown initialized" data-val="true" data-val-number="The field SortId must be a number." data-val-required="The SortId field is required." id="SortId" name="SortId"><option selected="selected" value="1">Nieuwste eerst</option><option value="2">Prijs oplopend</option></select></div> <select class="search-filter-data other-option radio sort-dropdown" data-val="true" data-val-number="The field SortId must be a number." data-val-required="The SortId field is required." id="SortId" name="SortId"><option selected="selected" value="1">Nieuwste eerst</option>
<option value="2">Prijs oplopend</option>
<option value="4">Prijs aflopend</option>
<option value="5">Oppervlakte</option>
<option value="6">Beschikbaar per</option>
</select> </div><div class="col s8 l9 no-padding-left">
